name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ubah ke 'master' jika nama branch utama Anda adalah master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Inject Firebase Config from Secret
        run: |
          echo "${{ secrets.FIREBASE_CONFIG_FILE }}" > firebase-config.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Mengunggah seluruh root direktori project

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4